server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/agrismart_db
    username: root
    password: Root@123

logging:
  level:
    root: INFO
    '[com.backend.AgriSmart]': DEBUG