server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agrismart_db
    username: root
    password: Root@123

logging:
  level:
    root: INFO
    '[com.backend.AgriSmart]': WARN